name: check for pipline changes

on:
  push:
    branches: [ci-test]
    pull-request : [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: setup node js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install
        working-directory: ./DevOps_Pipelines/

      - name: run test
        run: node test.js
        working-directory: ./DevOps_Pipelines/

        